services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: enterprise-copilot-db

    environment:
      POSTGRES_USER: copilot
      POSTGRES_PASSWORD: copilot_password
      POSTGRES_DB: knowledge_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: